# fly.toml app configuration file generated for elixircl-matebot on 2023-06-29T14:28:29-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "elixircl-matebot"
primary_region = "scl"
kill_signal = "SIGTERM"

[deploy]
  release_command = "/app/bin/migrate"

[env]
  PHX_HOST = "elixircl-matebot.fly.dev"
  PORT = "4000"

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 1000
