= 🧉 Mate For You

This project is a slim clone of https://heytaco.com/[HeyTaco] made in *Elixir*.

== Workflow
1. Add _Mate_ to _Discord_.
2. Write and include _:mate:_ emoji (🧉)  in your messages to show praise, appreciation, or to just simply put a smile on someone's face and include them in the message.

Example

[source,text]
----
Hey thanks for your help @huemul :mate:
----

== Features

=== Must

- [x] Users can receive any amount of mates 🧉 per day.
- [x] Users can give up to 5 mates 🧉 per day to any user.

=== Should
- [x] Have commands to show current stats for the user.

=== Possible

- [ ] Filter with hashtags
- [ ] Have API for Leaderboards (https://www.heytaco.chat/api)
- [ ] Leaderboard page with top receiving users (day, week, month, year).
- [ ] Leaderboard page with top giving users (day, week, month, year).

== Tech Stack

- https://discord.com/[Discord] (or compatibles like https://revolt.chat/[Revolt.chat]).
- Elixir 1.14
- Phoenix
- Nostrum
- PostgreSQL

== Example

image:https://github.com/ElixirCL/mate/assets/292738/271c99b9-733f-4ae4-8225-d1b4084c3d7c[Sent]

image:https://github.com/ElixirCL/mate/assets/292738/9bd58c1c-d001-4570-833b-33be3d702282[Stats]

== Commands

- `!top`: Show top 10 users in the week.
- `!stats`: Show current stats for the user

== License

https://www.gnu.org/licenses/agpl-3.0[image:https://img.shields.io/badge/License-AGPL%20v3-blue.svg[License: AGPL v3]]

== Credits

image:https://img.shields.io/badge/Proudly_Coded_in-🇨🇱_Chile-white?style=for-the-badge[Proudly Coded in - 🇨🇱 Chile]
